### ISSUE TITLE
Missing features todo list

### ISSUE THREAD

**Issue by hendricha** [hendricha/syfi#1]
- [x] Don't open empty tab if nothing is returned by syfi-cli
- [x] Throw a normal message if AppKernel or bootstrap.php.cache could not be found
- [x] app folder location should be configurable
- [x] locate twig shorthands
- [x] locate doctrine model shorthands
- [ ] if nothing is selected get the first relevant string around the caret
- [ ] parse 'use' for class names from the current file
- [ ] locate where a service id is defined
- [ ] handle translation source to target conversion somehow and open where translation is used
